pipeline{
    agent any
    stages {
        stage('Checkout from Git'){
            steps{
                git branch: 'master', url: 'https://github.com/HoangPhan10/Teris.git'
            }
        }
        stage('Terraform version'){
             steps{
                 sh 'terraform --version'
             }
        }
        stage('Terraform init'){
             steps{
                 dir('eks-terraform') {
                      sh 'terraform init'
                   }
             }
        }
        stage('Terraform validate'){
             steps{
                 dir('eks-terraform') {
                      sh 'terraform validate'
                   }
             }
        }
        stage('Terraform plan'){
             steps{
                 dir('eks-terraform') {
                      sh 'terraform plan'
                   }
             }
        }
        stage('Terraform apply/destroy'){
             steps{
                 dir('eks-terraform') {
                      sh 'terraform ${action} --auto-approve'
                   }
             }
        }
    }
}